package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	werror "github.com/palantir/witchcraft-go-error"
)

// Run this generator to update the "categories.go" file with content that matches the Java declarations in an
// "AuditCategoryConfiguration.java" file.
func main() {
	if len(os.Args) < 2 {
		_, _ = fmt.Fprintf(os.Stderr, "Usage: %s <path to input Java file>\n", os.Args[0])
		os.Exit(1)
	}

	if err := runLogic(os.Args[1]); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

const header = `// Copyright (c) 2025 Palantir Technologies. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by category_transform.go, DO NOT EDIT.

package audit3log

import (
	"context"

	"github.com/palantir/witchcraft-go-logging/conjure/foundry/audit/api/category"
	v2 "github.com/palantir/witchcraft-go-logging/conjure/foundry/audit/api/category/v2"
	categoriespkg "github.com/palantir/witchcraft-go-logging/wlog/auditlog/audit3log/internal/categories"
)

`

func runLogic(inputFilePath string) error {
	fBytes, err := os.ReadFile(inputFilePath)
	if err != nil {
		return werror.Wrap(err, "failed to read Java file", werror.SafeParam("inputFilePath", inputFilePath))
	}
	outBytes, err := convertJavaCategoryDefinitionToGo(fBytes)
	if err != nil {
		return werror.Wrap(err, "failed to convert Java category definitions to Go")
	}

	destFilePath := filepath.Join("..", "categories.go")
	if err := os.WriteFile(destFilePath, outBytes, 0644); err != nil {
		return werror.Wrap(err, "failed to write output file")
	}

	return nil
}

func convertJavaCategoryDefinitionToGo(javaFileBytes []byte) ([]byte, error) {
	var categoryDefs, categoryVisitors []string

	defineCategoryRegexp := regexp.MustCompile(`(?s)static final Category<[^>]+> ([^=]+) =\s*category\(\s*"([^"]+)",\s*[^,]+\)[^;]+`)
	for _, matchPart := range defineCategoryRegexp.FindAll(javaFileBytes, -1) {
		categoryDef, categoryVisitor, err := convertSingleJavaDefinitionToGo(string(matchPart))
		if err != nil {
			return nil, werror.Wrap(err, "failed to convert Java category")
		}
		categoryDefs = append(categoryDefs, categoryDef)
		categoryVisitors = append(categoryVisitors, categoryVisitor)
	}

	outBytes := &bytes.Buffer{}
	outBytes.WriteString(header)

	outBytes.WriteString(`var (`)
	outBytes.WriteString("\n")

	for idx, def := range categoryDefs {
		outBytes.WriteString("\t")
		outBytes.WriteString(def)
		if idx != len(categoryDefs)-1 {
			outBytes.WriteString("\n\n")
		}
	}

	outBytes.WriteString("\n")
	outBytes.WriteString(`)`)
	outBytes.WriteString("\n\n")

	for idx, visitor := range categoryVisitors {
		outBytes.WriteString(visitor)
		if idx != len(categoryDefs)-1 {
			outBytes.WriteString("\n\n")
		}
	}
	outBytes.WriteString("\n")

	return outBytes.Bytes(), nil
}

func convertSingleJavaDefinitionToGo(in string) (string, string, error) {
	categoryRegexp := regexp.MustCompile(`category\(\s*"([^"]+)",\s*([^.]+)\.class\)`)
	matched := categoryRegexp.FindStringSubmatch(in)
	if matched == nil {
		return "", "", fmt.Errorf("category did not match")
	}
	categoryName := matched[1]
	categoryClass := matched[2]

	//"createInfraTargets", Classification.RESOURCE, wrapList(CreateInfra::getCreateInfraTargets))
	categoryDefOut := fmt.Sprintf(`category%s = newCategoryInfo("%s", v2.NewAuditCategoryV2From%s)`, categoryClass, categoryName, categoryClass)
	if matches := regexp.MustCompile(`(?s)(optional|required)(Request|Response)\([^"]*"([^"]+)",\s*Classification\.([^,]+),.+?::get([^)]+)`).FindAllStringSubmatch(in, -1); matches != nil {
		categoryDefOut += ".\n"
		for idx, currMatch := range matches {
			optionalOrRequired := currMatch[1]
			requestOrResponse := currMatch[2]
			fieldName := currMatch[3]
			classification := currMatch[4]

			categoryDefOut += fmt.Sprintf(`				%s%s("%s", categoriespkg.Classification_%s, func(v v2.%s) any { return v.%s })`, optionalOrRequired, requestOrResponse, fieldName, classification, categoryClass, capitalize(fieldName))
			if idx != len(matches)-1 {
				categoryDefOut += ".\n"
			}
		}
	}

	pkgImport := "v2"
	if categoryClass == "Internal" {
		pkgImport = "category"
	}

	categoryVisitorOut := fmt.Sprintf("func (a *auditCategoryV2Visitor) Visit%s(ctx context.Context, v %s.%s) (Param, error) {\n", categoryClass, pkgImport, categoryClass)
	categoryVisitorOut += fmt.Sprintf("\treturn category%s.toParam(v), nil\n", categoryClass)
	categoryVisitorOut += "}"

	return categoryDefOut, categoryVisitorOut, nil
}

func capitalize(in string) string {
	if len(in) == 0 {
		return in
	}
	return strings.ToUpper(in[:1]) + in[1:]
}
