plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.44.0
        checksums:
          darwin-amd64: 764c96eaf44713445c40b6d6fe0b684050357a95e83bfa5d98769f62ea9903e2
          linux-amd64: 1168918b53528680cd57033a19f645ce250096548472d7c89aa376ba0049e5dc
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.24.0
        checksums:
          darwin-amd64: 6982bb6578ca8c72b8f96777623f218071cc7f6da7fb4c6ac37ee117e56b0bbc
          linux-amd64: b61352cf93086972801319fcb84494639217d47b54656bbdf6d2a82bbf853099
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
