// This file was generated by Conjure and should not be manually edited.

package logging

import (
	"context"
	"fmt"
	"io"

	"github.com/palantir/conjure-go/v6/dj"
)

type Diagnostic struct {
	typ        string
	generic    *GenericDiagnostic
	threadDump *ThreadDumpV1
}

func (u Diagnostic) MarshalJSON() ([]byte, error) {
	out := make([]byte, 0)
	if _, err := u.WriteJSON(dj.NewAppender(&out)); err != nil {
		return nil, err
	}
	return out, dj.Valid(out)
}

func (u Diagnostic) WriteJSON(w io.Writer) (int, error) {
	var out int
	n0, err := dj.WriteOpenObject(w)
	if err != nil {
		return 0, err
	}
	out += n0
	switch u.typ {
	case "generic":
		n1, err := dj.WriteLiteral(w, "\"type\":\"generic\"")
		if err != nil {
			return 0, err
		}
		out += n1
		if u.generic != nil {
			n2, err := dj.WriteLiteral(w, ",\"generic\":")
			if err != nil {
				return 0, err
			}
			out += n2
			unionVal := *u.generic
			n3, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n3
		}
	case "threadDump":
		n4, err := dj.WriteLiteral(w, "\"type\":\"threadDump\"")
		if err != nil {
			return 0, err
		}
		out += n4
		if u.threadDump != nil {
			n5, err := dj.WriteLiteral(w, ",\"threadDump\":")
			if err != nil {
				return 0, err
			}
			out += n5
			unionVal := *u.threadDump
			n6, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n6
		}
	default:
		n7, err := dj.WriteLiteral(w, "\"type\":")
		if err != nil {
			return 0, err
		}
		out += n7
		n8, err := dj.WriteString(w, (u.typ))
		if err != nil {
			return 0, err
		}
		out += n8
	}
	n9, err := dj.WriteCloseObject(w)
	if err != nil {
		return 0, err
	}
	out += n9
	return out, nil
}

func (u Diagnostic) MarshalYAML() (interface{}, error) {
	return dj.MarshalYAML(u)
}

func (u *Diagnostic) UnmarshalJSON(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *Diagnostic) UnmarshalJSONStrict(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *Diagnostic) UnmarshalJSONString(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *Diagnostic) UnmarshalJSONStringStrict(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *Diagnostic) UnmarshalJSONResult(value dj.Result, disallowUnknownFields bool) error {
	var seenType bool
	var seenGeneric bool
	var seenThreadDump bool
	var unknownFields []string
	iter, idx, err := value.ObjectIterator(0)
	if err != nil {
		return err
	}
	for iter.HasNext(value, idx) {
		var fieldKey, fieldValue dj.Result
		fieldKey, fieldValue, idx, err = iter.Next(value, idx)
		if err != nil {
			return err
		}
		keyString, err := fieldKey.String()
		if err != nil {
			return err
		}
		switch keyString {
		case "type":
			if seenType {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field Diagnostic[\"type\"]")
			}
			seenType = true
			u.typ, err = fieldValue.String()
			if err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field Diagnostic[\"type\"]", err)
			}
		case "generic":
			if seenGeneric {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field Diagnostic[\"generic\"]")
			}
			seenGeneric = true
			var unionVal GenericDiagnostic
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field Diagnostic[\"generic\"]", err)
			}
			u.generic = &unionVal
		case "threadDump":
			if seenThreadDump {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field Diagnostic[\"threadDump\"]")
			}
			seenThreadDump = true
			var unionVal ThreadDumpV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field Diagnostic[\"threadDump\"]", err)
			}
			u.threadDump = &unionVal
		default:
			if disallowUnknownFields {
				unknownFields = append(unknownFields, keyString)
			}
		}
	}
	var missingFields []string
	if !seenType {
		missingFields = append(missingFields, "type")
	}
	if u.typ == "generic" && !seenGeneric {
		missingFields = append(missingFields, "generic")
	}
	if u.typ == "threadDump" && !seenThreadDump {
		missingFields = append(missingFields, "threadDump")
	}
	if len(missingFields) > 0 {
		return dj.NewUnmarshalMissingFieldsError(value, "Diagnostic", missingFields)
	}
	if disallowUnknownFields && len(unknownFields) > 0 {
		return dj.NewUnmarshalUnknownFieldsError(value, "Diagnostic", unknownFields)
	}
	return nil
}

func (u *Diagnostic) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return dj.UnmarshalYAML(u, unmarshal)
}

func (u *Diagnostic) AcceptFuncs(genericFunc func(GenericDiagnostic) error, threadDumpFunc func(ThreadDumpV1) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "generic":
		if u.generic == nil {
			return fmt.Errorf("field \"generic\" is required")
		}
		return genericFunc(*u.generic)
	case "threadDump":
		if u.threadDump == nil {
			return fmt.Errorf("field \"threadDump\" is required")
		}
		return threadDumpFunc(*u.threadDump)
	}
}

func (u *Diagnostic) GenericNoopSuccess(_ GenericDiagnostic) error {
	return nil
}

func (u *Diagnostic) ThreadDumpNoopSuccess(_ ThreadDumpV1) error {
	return nil
}

func (u *Diagnostic) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *Diagnostic) Accept(v DiagnosticVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "generic":
		if u.generic == nil {
			return fmt.Errorf("field \"generic\" is required")
		}
		return v.VisitGeneric(*u.generic)
	case "threadDump":
		if u.threadDump == nil {
			return fmt.Errorf("field \"threadDump\" is required")
		}
		return v.VisitThreadDump(*u.threadDump)
	}
}

type DiagnosticVisitor interface {
	VisitGeneric(v GenericDiagnostic) error
	VisitThreadDump(v ThreadDumpV1) error
	VisitUnknown(typeName string) error
}

func (u *Diagnostic) AcceptWithContext(ctx context.Context, v DiagnosticVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "generic":
		if u.generic == nil {
			return fmt.Errorf("field \"generic\" is required")
		}
		return v.VisitGenericWithContext(ctx, *u.generic)
	case "threadDump":
		if u.threadDump == nil {
			return fmt.Errorf("field \"threadDump\" is required")
		}
		return v.VisitThreadDumpWithContext(ctx, *u.threadDump)
	}
}

type DiagnosticVisitorWithContext interface {
	VisitGenericWithContext(ctx context.Context, v GenericDiagnostic) error
	VisitThreadDumpWithContext(ctx context.Context, v ThreadDumpV1) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewDiagnosticFromGeneric(v GenericDiagnostic) Diagnostic {
	return Diagnostic{typ: "generic", generic: &v}
}

func NewDiagnosticFromThreadDump(v ThreadDumpV1) Diagnostic {
	return Diagnostic{typ: "threadDump", threadDump: &v}
}

type RequestLog struct {
	typ string
	v1  *RequestLogV1
	v2  *RequestLogV2
}

func (u RequestLog) MarshalJSON() ([]byte, error) {
	out := make([]byte, 0)
	if _, err := u.WriteJSON(dj.NewAppender(&out)); err != nil {
		return nil, err
	}
	return out, dj.Valid(out)
}

func (u RequestLog) WriteJSON(w io.Writer) (int, error) {
	var out int
	n0, err := dj.WriteOpenObject(w)
	if err != nil {
		return 0, err
	}
	out += n0
	switch u.typ {
	case "v1":
		n1, err := dj.WriteLiteral(w, "\"type\":\"v1\"")
		if err != nil {
			return 0, err
		}
		out += n1
		if u.v1 != nil {
			n2, err := dj.WriteLiteral(w, ",\"v1\":")
			if err != nil {
				return 0, err
			}
			out += n2
			unionVal := *u.v1
			n3, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n3
		}
	case "v2":
		n4, err := dj.WriteLiteral(w, "\"type\":\"v2\"")
		if err != nil {
			return 0, err
		}
		out += n4
		if u.v2 != nil {
			n5, err := dj.WriteLiteral(w, ",\"v2\":")
			if err != nil {
				return 0, err
			}
			out += n5
			unionVal := *u.v2
			n6, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n6
		}
	default:
		n7, err := dj.WriteLiteral(w, "\"type\":")
		if err != nil {
			return 0, err
		}
		out += n7
		n8, err := dj.WriteString(w, (u.typ))
		if err != nil {
			return 0, err
		}
		out += n8
	}
	n9, err := dj.WriteCloseObject(w)
	if err != nil {
		return 0, err
	}
	out += n9
	return out, nil
}

func (u RequestLog) MarshalYAML() (interface{}, error) {
	return dj.MarshalYAML(u)
}

func (u *RequestLog) UnmarshalJSON(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *RequestLog) UnmarshalJSONStrict(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *RequestLog) UnmarshalJSONString(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *RequestLog) UnmarshalJSONStringStrict(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *RequestLog) UnmarshalJSONResult(value dj.Result, disallowUnknownFields bool) error {
	var seenType bool
	var seenV1 bool
	var seenV2 bool
	var unknownFields []string
	iter, idx, err := value.ObjectIterator(0)
	if err != nil {
		return err
	}
	for iter.HasNext(value, idx) {
		var fieldKey, fieldValue dj.Result
		fieldKey, fieldValue, idx, err = iter.Next(value, idx)
		if err != nil {
			return err
		}
		keyString, err := fieldKey.String()
		if err != nil {
			return err
		}
		switch keyString {
		case "type":
			if seenType {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field RequestLog[\"type\"]")
			}
			seenType = true
			u.typ, err = fieldValue.String()
			if err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field RequestLog[\"type\"]", err)
			}
		case "v1":
			if seenV1 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field RequestLog[\"v1\"]")
			}
			seenV1 = true
			var unionVal RequestLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field RequestLog[\"v1\"]", err)
			}
			u.v1 = &unionVal
		case "v2":
			if seenV2 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field RequestLog[\"v2\"]")
			}
			seenV2 = true
			var unionVal RequestLogV2
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field RequestLog[\"v2\"]", err)
			}
			u.v2 = &unionVal
		default:
			if disallowUnknownFields {
				unknownFields = append(unknownFields, keyString)
			}
		}
	}
	var missingFields []string
	if !seenType {
		missingFields = append(missingFields, "type")
	}
	if u.typ == "v1" && !seenV1 {
		missingFields = append(missingFields, "v1")
	}
	if u.typ == "v2" && !seenV2 {
		missingFields = append(missingFields, "v2")
	}
	if len(missingFields) > 0 {
		return dj.NewUnmarshalMissingFieldsError(value, "RequestLog", missingFields)
	}
	if disallowUnknownFields && len(unknownFields) > 0 {
		return dj.NewUnmarshalUnknownFieldsError(value, "RequestLog", unknownFields)
	}
	return nil
}

func (u *RequestLog) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return dj.UnmarshalYAML(u, unmarshal)
}

func (u *RequestLog) AcceptFuncs(v1Func func(RequestLogV1) error, v2Func func(RequestLogV2) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "v1":
		if u.v1 == nil {
			return fmt.Errorf("field \"v1\" is required")
		}
		return v1Func(*u.v1)
	case "v2":
		if u.v2 == nil {
			return fmt.Errorf("field \"v2\" is required")
		}
		return v2Func(*u.v2)
	}
}

func (u *RequestLog) V1NoopSuccess(_ RequestLogV1) error {
	return nil
}

func (u *RequestLog) V2NoopSuccess(_ RequestLogV2) error {
	return nil
}

func (u *RequestLog) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *RequestLog) Accept(v RequestLogVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "v1":
		if u.v1 == nil {
			return fmt.Errorf("field \"v1\" is required")
		}
		return v.VisitV1(*u.v1)
	case "v2":
		if u.v2 == nil {
			return fmt.Errorf("field \"v2\" is required")
		}
		return v.VisitV2(*u.v2)
	}
}

type RequestLogVisitor interface {
	VisitV1(v RequestLogV1) error
	VisitV2(v RequestLogV2) error
	VisitUnknown(typeName string) error
}

func (u *RequestLog) AcceptWithContext(ctx context.Context, v RequestLogVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "v1":
		if u.v1 == nil {
			return fmt.Errorf("field \"v1\" is required")
		}
		return v.VisitV1WithContext(ctx, *u.v1)
	case "v2":
		if u.v2 == nil {
			return fmt.Errorf("field \"v2\" is required")
		}
		return v.VisitV2WithContext(ctx, *u.v2)
	}
}

type RequestLogVisitorWithContext interface {
	VisitV1WithContext(ctx context.Context, v RequestLogV1) error
	VisitV2WithContext(ctx context.Context, v RequestLogV2) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewRequestLogFromV1(v RequestLogV1) RequestLog {
	return RequestLog{typ: "v1", v1: &v}
}

func NewRequestLogFromV2(v RequestLogV2) RequestLog {
	return RequestLog{typ: "v2", v2: &v}
}

// Union type containing log types that are logged to event.log.
type UnionEventLog struct {
	typ        string
	eventLog   *EventLogV1
	eventLogV2 *EventLogV2
	beaconLog  *BeaconLogV1
}

func (u UnionEventLog) MarshalJSON() ([]byte, error) {
	out := make([]byte, 0)
	if _, err := u.WriteJSON(dj.NewAppender(&out)); err != nil {
		return nil, err
	}
	return out, dj.Valid(out)
}

func (u UnionEventLog) WriteJSON(w io.Writer) (int, error) {
	var out int
	n0, err := dj.WriteOpenObject(w)
	if err != nil {
		return 0, err
	}
	out += n0
	switch u.typ {
	case "eventLog":
		n1, err := dj.WriteLiteral(w, "\"type\":\"eventLog\"")
		if err != nil {
			return 0, err
		}
		out += n1
		if u.eventLog != nil {
			n2, err := dj.WriteLiteral(w, ",\"eventLog\":")
			if err != nil {
				return 0, err
			}
			out += n2
			unionVal := *u.eventLog
			n3, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n3
		}
	case "eventLogV2":
		n4, err := dj.WriteLiteral(w, "\"type\":\"eventLogV2\"")
		if err != nil {
			return 0, err
		}
		out += n4
		if u.eventLogV2 != nil {
			n5, err := dj.WriteLiteral(w, ",\"eventLogV2\":")
			if err != nil {
				return 0, err
			}
			out += n5
			unionVal := *u.eventLogV2
			n6, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n6
		}
	case "beaconLog":
		n7, err := dj.WriteLiteral(w, "\"type\":\"beaconLog\"")
		if err != nil {
			return 0, err
		}
		out += n7
		if u.beaconLog != nil {
			n8, err := dj.WriteLiteral(w, ",\"beaconLog\":")
			if err != nil {
				return 0, err
			}
			out += n8
			unionVal := *u.beaconLog
			n9, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n9
		}
	default:
		n10, err := dj.WriteLiteral(w, "\"type\":")
		if err != nil {
			return 0, err
		}
		out += n10
		n11, err := dj.WriteString(w, (u.typ))
		if err != nil {
			return 0, err
		}
		out += n11
	}
	n12, err := dj.WriteCloseObject(w)
	if err != nil {
		return 0, err
	}
	out += n12
	return out, nil
}

func (u UnionEventLog) MarshalYAML() (interface{}, error) {
	return dj.MarshalYAML(u)
}

func (u *UnionEventLog) UnmarshalJSON(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *UnionEventLog) UnmarshalJSONStrict(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *UnionEventLog) UnmarshalJSONString(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *UnionEventLog) UnmarshalJSONStringStrict(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *UnionEventLog) UnmarshalJSONResult(value dj.Result, disallowUnknownFields bool) error {
	var seenType bool
	var seenEventLog bool
	var seenEventLogV2 bool
	var seenBeaconLog bool
	var unknownFields []string
	iter, idx, err := value.ObjectIterator(0)
	if err != nil {
		return err
	}
	for iter.HasNext(value, idx) {
		var fieldKey, fieldValue dj.Result
		fieldKey, fieldValue, idx, err = iter.Next(value, idx)
		if err != nil {
			return err
		}
		keyString, err := fieldKey.String()
		if err != nil {
			return err
		}
		switch keyString {
		case "type":
			if seenType {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field UnionEventLog[\"type\"]")
			}
			seenType = true
			u.typ, err = fieldValue.String()
			if err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field UnionEventLog[\"type\"]", err)
			}
		case "eventLog":
			if seenEventLog {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field UnionEventLog[\"eventLog\"]")
			}
			seenEventLog = true
			var unionVal EventLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field UnionEventLog[\"eventLog\"]", err)
			}
			u.eventLog = &unionVal
		case "eventLogV2":
			if seenEventLogV2 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field UnionEventLog[\"eventLogV2\"]")
			}
			seenEventLogV2 = true
			var unionVal EventLogV2
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field UnionEventLog[\"eventLogV2\"]", err)
			}
			u.eventLogV2 = &unionVal
		case "beaconLog":
			if seenBeaconLog {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field UnionEventLog[\"beaconLog\"]")
			}
			seenBeaconLog = true
			var unionVal BeaconLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field UnionEventLog[\"beaconLog\"]", err)
			}
			u.beaconLog = &unionVal
		default:
			if disallowUnknownFields {
				unknownFields = append(unknownFields, keyString)
			}
		}
	}
	var missingFields []string
	if !seenType {
		missingFields = append(missingFields, "type")
	}
	if u.typ == "eventLog" && !seenEventLog {
		missingFields = append(missingFields, "eventLog")
	}
	if u.typ == "eventLogV2" && !seenEventLogV2 {
		missingFields = append(missingFields, "eventLogV2")
	}
	if u.typ == "beaconLog" && !seenBeaconLog {
		missingFields = append(missingFields, "beaconLog")
	}
	if len(missingFields) > 0 {
		return dj.NewUnmarshalMissingFieldsError(value, "UnionEventLog", missingFields)
	}
	if disallowUnknownFields && len(unknownFields) > 0 {
		return dj.NewUnmarshalUnknownFieldsError(value, "UnionEventLog", unknownFields)
	}
	return nil
}

func (u *UnionEventLog) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return dj.UnmarshalYAML(u, unmarshal)
}

func (u *UnionEventLog) AcceptFuncs(eventLogFunc func(EventLogV1) error, eventLogV2Func func(EventLogV2) error, beaconLogFunc func(BeaconLogV1) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "eventLog":
		if u.eventLog == nil {
			return fmt.Errorf("field \"eventLog\" is required")
		}
		return eventLogFunc(*u.eventLog)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return eventLogV2Func(*u.eventLogV2)
	case "beaconLog":
		if u.beaconLog == nil {
			return fmt.Errorf("field \"beaconLog\" is required")
		}
		return beaconLogFunc(*u.beaconLog)
	}
}

func (u *UnionEventLog) EventLogNoopSuccess(_ EventLogV1) error {
	return nil
}

func (u *UnionEventLog) EventLogV2NoopSuccess(_ EventLogV2) error {
	return nil
}

func (u *UnionEventLog) BeaconLogNoopSuccess(_ BeaconLogV1) error {
	return nil
}

func (u *UnionEventLog) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *UnionEventLog) Accept(v UnionEventLogVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "eventLog":
		if u.eventLog == nil {
			return fmt.Errorf("field \"eventLog\" is required")
		}
		return v.VisitEventLog(*u.eventLog)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return v.VisitEventLogV2(*u.eventLogV2)
	case "beaconLog":
		if u.beaconLog == nil {
			return fmt.Errorf("field \"beaconLog\" is required")
		}
		return v.VisitBeaconLog(*u.beaconLog)
	}
}

type UnionEventLogVisitor interface {
	VisitEventLog(v EventLogV1) error
	VisitEventLogV2(v EventLogV2) error
	VisitBeaconLog(v BeaconLogV1) error
	VisitUnknown(typeName string) error
}

func (u *UnionEventLog) AcceptWithContext(ctx context.Context, v UnionEventLogVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "eventLog":
		if u.eventLog == nil {
			return fmt.Errorf("field \"eventLog\" is required")
		}
		return v.VisitEventLogWithContext(ctx, *u.eventLog)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return v.VisitEventLogV2WithContext(ctx, *u.eventLogV2)
	case "beaconLog":
		if u.beaconLog == nil {
			return fmt.Errorf("field \"beaconLog\" is required")
		}
		return v.VisitBeaconLogWithContext(ctx, *u.beaconLog)
	}
}

type UnionEventLogVisitorWithContext interface {
	VisitEventLogWithContext(ctx context.Context, v EventLogV1) error
	VisitEventLogV2WithContext(ctx context.Context, v EventLogV2) error
	VisitBeaconLogWithContext(ctx context.Context, v BeaconLogV1) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewUnionEventLogFromEventLog(v EventLogV1) UnionEventLog {
	return UnionEventLog{typ: "eventLog", eventLog: &v}
}

func NewUnionEventLogFromEventLogV2(v EventLogV2) UnionEventLog {
	return UnionEventLog{typ: "eventLogV2", eventLogV2: &v}
}

func NewUnionEventLogFromBeaconLog(v BeaconLogV1) UnionEventLog {
	return UnionEventLog{typ: "beaconLog", beaconLog: &v}
}

type WrappedLogV1Payload struct {
	typ             string
	serviceLogV1    *ServiceLogV1
	requestLogV2    *RequestLogV2
	traceLogV1      *TraceLogV1
	eventLogV2      *EventLogV2
	metricLogV1     *MetricLogV1
	auditLogV2      *AuditLogV2
	diagnosticLogV1 *DiagnosticLogV1
}

func (u WrappedLogV1Payload) MarshalJSON() ([]byte, error) {
	out := make([]byte, 0)
	if _, err := u.WriteJSON(dj.NewAppender(&out)); err != nil {
		return nil, err
	}
	return out, dj.Valid(out)
}

func (u WrappedLogV1Payload) WriteJSON(w io.Writer) (int, error) {
	var out int
	n0, err := dj.WriteOpenObject(w)
	if err != nil {
		return 0, err
	}
	out += n0
	switch u.typ {
	case "serviceLogV1":
		n1, err := dj.WriteLiteral(w, "\"type\":\"serviceLogV1\"")
		if err != nil {
			return 0, err
		}
		out += n1
		if u.serviceLogV1 != nil {
			n2, err := dj.WriteLiteral(w, ",\"serviceLogV1\":")
			if err != nil {
				return 0, err
			}
			out += n2
			unionVal := *u.serviceLogV1
			n3, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n3
		}
	case "requestLogV2":
		n4, err := dj.WriteLiteral(w, "\"type\":\"requestLogV2\"")
		if err != nil {
			return 0, err
		}
		out += n4
		if u.requestLogV2 != nil {
			n5, err := dj.WriteLiteral(w, ",\"requestLogV2\":")
			if err != nil {
				return 0, err
			}
			out += n5
			unionVal := *u.requestLogV2
			n6, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n6
		}
	case "traceLogV1":
		n7, err := dj.WriteLiteral(w, "\"type\":\"traceLogV1\"")
		if err != nil {
			return 0, err
		}
		out += n7
		if u.traceLogV1 != nil {
			n8, err := dj.WriteLiteral(w, ",\"traceLogV1\":")
			if err != nil {
				return 0, err
			}
			out += n8
			unionVal := *u.traceLogV1
			n9, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n9
		}
	case "eventLogV2":
		n10, err := dj.WriteLiteral(w, "\"type\":\"eventLogV2\"")
		if err != nil {
			return 0, err
		}
		out += n10
		if u.eventLogV2 != nil {
			n11, err := dj.WriteLiteral(w, ",\"eventLogV2\":")
			if err != nil {
				return 0, err
			}
			out += n11
			unionVal := *u.eventLogV2
			n12, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n12
		}
	case "metricLogV1":
		n13, err := dj.WriteLiteral(w, "\"type\":\"metricLogV1\"")
		if err != nil {
			return 0, err
		}
		out += n13
		if u.metricLogV1 != nil {
			n14, err := dj.WriteLiteral(w, ",\"metricLogV1\":")
			if err != nil {
				return 0, err
			}
			out += n14
			unionVal := *u.metricLogV1
			n15, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n15
		}
	case "auditLogV2":
		n16, err := dj.WriteLiteral(w, "\"type\":\"auditLogV2\"")
		if err != nil {
			return 0, err
		}
		out += n16
		if u.auditLogV2 != nil {
			n17, err := dj.WriteLiteral(w, ",\"auditLogV2\":")
			if err != nil {
				return 0, err
			}
			out += n17
			unionVal := *u.auditLogV2
			n18, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n18
		}
	case "diagnosticLogV1":
		n19, err := dj.WriteLiteral(w, "\"type\":\"diagnosticLogV1\"")
		if err != nil {
			return 0, err
		}
		out += n19
		if u.diagnosticLogV1 != nil {
			n20, err := dj.WriteLiteral(w, ",\"diagnosticLogV1\":")
			if err != nil {
				return 0, err
			}
			out += n20
			unionVal := *u.diagnosticLogV1
			n21, err := unionVal.WriteJSON(w)
			if err != nil {
				return 0, err
			}
			out += n21
		}
	default:
		n22, err := dj.WriteLiteral(w, "\"type\":")
		if err != nil {
			return 0, err
		}
		out += n22
		n23, err := dj.WriteString(w, (u.typ))
		if err != nil {
			return 0, err
		}
		out += n23
	}
	n24, err := dj.WriteCloseObject(w)
	if err != nil {
		return 0, err
	}
	out += n24
	return out, nil
}

func (u WrappedLogV1Payload) MarshalYAML() (interface{}, error) {
	return dj.MarshalYAML(u)
}

func (u *WrappedLogV1Payload) UnmarshalJSON(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *WrappedLogV1Payload) UnmarshalJSONStrict(data []byte) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *WrappedLogV1Payload) UnmarshalJSONString(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, false)
}

func (u *WrappedLogV1Payload) UnmarshalJSONStringStrict(data string) error {
	value, err := dj.Parse(data)
	if err != nil {
		return err
	}
	return u.UnmarshalJSONResult(value, true)
}

func (u *WrappedLogV1Payload) UnmarshalJSONResult(value dj.Result, disallowUnknownFields bool) error {
	var seenType bool
	var seenServiceLogV1 bool
	var seenRequestLogV2 bool
	var seenTraceLogV1 bool
	var seenEventLogV2 bool
	var seenMetricLogV1 bool
	var seenAuditLogV2 bool
	var seenDiagnosticLogV1 bool
	var unknownFields []string
	iter, idx, err := value.ObjectIterator(0)
	if err != nil {
		return err
	}
	for iter.HasNext(value, idx) {
		var fieldKey, fieldValue dj.Result
		fieldKey, fieldValue, idx, err = iter.Next(value, idx)
		if err != nil {
			return err
		}
		keyString, err := fieldKey.String()
		if err != nil {
			return err
		}
		switch keyString {
		case "type":
			if seenType {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"type\"]")
			}
			seenType = true
			u.typ, err = fieldValue.String()
			if err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"type\"]", err)
			}
		case "serviceLogV1":
			if seenServiceLogV1 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"serviceLogV1\"]")
			}
			seenServiceLogV1 = true
			var unionVal ServiceLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"serviceLogV1\"]", err)
			}
			u.serviceLogV1 = &unionVal
		case "requestLogV2":
			if seenRequestLogV2 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"requestLogV2\"]")
			}
			seenRequestLogV2 = true
			var unionVal RequestLogV2
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"requestLogV2\"]", err)
			}
			u.requestLogV2 = &unionVal
		case "traceLogV1":
			if seenTraceLogV1 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"traceLogV1\"]")
			}
			seenTraceLogV1 = true
			var unionVal TraceLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"traceLogV1\"]", err)
			}
			u.traceLogV1 = &unionVal
		case "eventLogV2":
			if seenEventLogV2 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"eventLogV2\"]")
			}
			seenEventLogV2 = true
			var unionVal EventLogV2
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"eventLogV2\"]", err)
			}
			u.eventLogV2 = &unionVal
		case "metricLogV1":
			if seenMetricLogV1 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"metricLogV1\"]")
			}
			seenMetricLogV1 = true
			var unionVal MetricLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"metricLogV1\"]", err)
			}
			u.metricLogV1 = &unionVal
		case "auditLogV2":
			if seenAuditLogV2 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"auditLogV2\"]")
			}
			seenAuditLogV2 = true
			var unionVal AuditLogV2
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"auditLogV2\"]", err)
			}
			u.auditLogV2 = &unionVal
		case "diagnosticLogV1":
			if seenDiagnosticLogV1 {
				return dj.NewUnmarshalDuplicateFieldError(fieldKey, "field WrappedLogV1Payload[\"diagnosticLogV1\"]")
			}
			seenDiagnosticLogV1 = true
			var unionVal DiagnosticLogV1
			if err := unionVal.UnmarshalJSONResult(fieldValue, disallowUnknownFields); err != nil {
				return dj.NewUnmarshalFieldError(fieldValue, "field WrappedLogV1Payload[\"diagnosticLogV1\"]", err)
			}
			u.diagnosticLogV1 = &unionVal
		default:
			if disallowUnknownFields {
				unknownFields = append(unknownFields, keyString)
			}
		}
	}
	var missingFields []string
	if !seenType {
		missingFields = append(missingFields, "type")
	}
	if u.typ == "serviceLogV1" && !seenServiceLogV1 {
		missingFields = append(missingFields, "serviceLogV1")
	}
	if u.typ == "requestLogV2" && !seenRequestLogV2 {
		missingFields = append(missingFields, "requestLogV2")
	}
	if u.typ == "traceLogV1" && !seenTraceLogV1 {
		missingFields = append(missingFields, "traceLogV1")
	}
	if u.typ == "eventLogV2" && !seenEventLogV2 {
		missingFields = append(missingFields, "eventLogV2")
	}
	if u.typ == "metricLogV1" && !seenMetricLogV1 {
		missingFields = append(missingFields, "metricLogV1")
	}
	if u.typ == "auditLogV2" && !seenAuditLogV2 {
		missingFields = append(missingFields, "auditLogV2")
	}
	if u.typ == "diagnosticLogV1" && !seenDiagnosticLogV1 {
		missingFields = append(missingFields, "diagnosticLogV1")
	}
	if len(missingFields) > 0 {
		return dj.NewUnmarshalMissingFieldsError(value, "WrappedLogV1Payload", missingFields)
	}
	if disallowUnknownFields && len(unknownFields) > 0 {
		return dj.NewUnmarshalUnknownFieldsError(value, "WrappedLogV1Payload", unknownFields)
	}
	return nil
}

func (u *WrappedLogV1Payload) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return dj.UnmarshalYAML(u, unmarshal)
}

func (u *WrappedLogV1Payload) AcceptFuncs(serviceLogV1Func func(ServiceLogV1) error, requestLogV2Func func(RequestLogV2) error, traceLogV1Func func(TraceLogV1) error, eventLogV2Func func(EventLogV2) error, metricLogV1Func func(MetricLogV1) error, auditLogV2Func func(AuditLogV2) error, diagnosticLogV1Func func(DiagnosticLogV1) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "serviceLogV1":
		if u.serviceLogV1 == nil {
			return fmt.Errorf("field \"serviceLogV1\" is required")
		}
		return serviceLogV1Func(*u.serviceLogV1)
	case "requestLogV2":
		if u.requestLogV2 == nil {
			return fmt.Errorf("field \"requestLogV2\" is required")
		}
		return requestLogV2Func(*u.requestLogV2)
	case "traceLogV1":
		if u.traceLogV1 == nil {
			return fmt.Errorf("field \"traceLogV1\" is required")
		}
		return traceLogV1Func(*u.traceLogV1)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return eventLogV2Func(*u.eventLogV2)
	case "metricLogV1":
		if u.metricLogV1 == nil {
			return fmt.Errorf("field \"metricLogV1\" is required")
		}
		return metricLogV1Func(*u.metricLogV1)
	case "auditLogV2":
		if u.auditLogV2 == nil {
			return fmt.Errorf("field \"auditLogV2\" is required")
		}
		return auditLogV2Func(*u.auditLogV2)
	case "diagnosticLogV1":
		if u.diagnosticLogV1 == nil {
			return fmt.Errorf("field \"diagnosticLogV1\" is required")
		}
		return diagnosticLogV1Func(*u.diagnosticLogV1)
	}
}

func (u *WrappedLogV1Payload) ServiceLogV1NoopSuccess(_ ServiceLogV1) error {
	return nil
}

func (u *WrappedLogV1Payload) RequestLogV2NoopSuccess(_ RequestLogV2) error {
	return nil
}

func (u *WrappedLogV1Payload) TraceLogV1NoopSuccess(_ TraceLogV1) error {
	return nil
}

func (u *WrappedLogV1Payload) EventLogV2NoopSuccess(_ EventLogV2) error {
	return nil
}

func (u *WrappedLogV1Payload) MetricLogV1NoopSuccess(_ MetricLogV1) error {
	return nil
}

func (u *WrappedLogV1Payload) AuditLogV2NoopSuccess(_ AuditLogV2) error {
	return nil
}

func (u *WrappedLogV1Payload) DiagnosticLogV1NoopSuccess(_ DiagnosticLogV1) error {
	return nil
}

func (u *WrappedLogV1Payload) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *WrappedLogV1Payload) Accept(v WrappedLogV1PayloadVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "serviceLogV1":
		if u.serviceLogV1 == nil {
			return fmt.Errorf("field \"serviceLogV1\" is required")
		}
		return v.VisitServiceLogV1(*u.serviceLogV1)
	case "requestLogV2":
		if u.requestLogV2 == nil {
			return fmt.Errorf("field \"requestLogV2\" is required")
		}
		return v.VisitRequestLogV2(*u.requestLogV2)
	case "traceLogV1":
		if u.traceLogV1 == nil {
			return fmt.Errorf("field \"traceLogV1\" is required")
		}
		return v.VisitTraceLogV1(*u.traceLogV1)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return v.VisitEventLogV2(*u.eventLogV2)
	case "metricLogV1":
		if u.metricLogV1 == nil {
			return fmt.Errorf("field \"metricLogV1\" is required")
		}
		return v.VisitMetricLogV1(*u.metricLogV1)
	case "auditLogV2":
		if u.auditLogV2 == nil {
			return fmt.Errorf("field \"auditLogV2\" is required")
		}
		return v.VisitAuditLogV2(*u.auditLogV2)
	case "diagnosticLogV1":
		if u.diagnosticLogV1 == nil {
			return fmt.Errorf("field \"diagnosticLogV1\" is required")
		}
		return v.VisitDiagnosticLogV1(*u.diagnosticLogV1)
	}
}

type WrappedLogV1PayloadVisitor interface {
	VisitServiceLogV1(v ServiceLogV1) error
	VisitRequestLogV2(v RequestLogV2) error
	VisitTraceLogV1(v TraceLogV1) error
	VisitEventLogV2(v EventLogV2) error
	VisitMetricLogV1(v MetricLogV1) error
	VisitAuditLogV2(v AuditLogV2) error
	VisitDiagnosticLogV1(v DiagnosticLogV1) error
	VisitUnknown(typeName string) error
}

func (u *WrappedLogV1Payload) AcceptWithContext(ctx context.Context, v WrappedLogV1PayloadVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "serviceLogV1":
		if u.serviceLogV1 == nil {
			return fmt.Errorf("field \"serviceLogV1\" is required")
		}
		return v.VisitServiceLogV1WithContext(ctx, *u.serviceLogV1)
	case "requestLogV2":
		if u.requestLogV2 == nil {
			return fmt.Errorf("field \"requestLogV2\" is required")
		}
		return v.VisitRequestLogV2WithContext(ctx, *u.requestLogV2)
	case "traceLogV1":
		if u.traceLogV1 == nil {
			return fmt.Errorf("field \"traceLogV1\" is required")
		}
		return v.VisitTraceLogV1WithContext(ctx, *u.traceLogV1)
	case "eventLogV2":
		if u.eventLogV2 == nil {
			return fmt.Errorf("field \"eventLogV2\" is required")
		}
		return v.VisitEventLogV2WithContext(ctx, *u.eventLogV2)
	case "metricLogV1":
		if u.metricLogV1 == nil {
			return fmt.Errorf("field \"metricLogV1\" is required")
		}
		return v.VisitMetricLogV1WithContext(ctx, *u.metricLogV1)
	case "auditLogV2":
		if u.auditLogV2 == nil {
			return fmt.Errorf("field \"auditLogV2\" is required")
		}
		return v.VisitAuditLogV2WithContext(ctx, *u.auditLogV2)
	case "diagnosticLogV1":
		if u.diagnosticLogV1 == nil {
			return fmt.Errorf("field \"diagnosticLogV1\" is required")
		}
		return v.VisitDiagnosticLogV1WithContext(ctx, *u.diagnosticLogV1)
	}
}

type WrappedLogV1PayloadVisitorWithContext interface {
	VisitServiceLogV1WithContext(ctx context.Context, v ServiceLogV1) error
	VisitRequestLogV2WithContext(ctx context.Context, v RequestLogV2) error
	VisitTraceLogV1WithContext(ctx context.Context, v TraceLogV1) error
	VisitEventLogV2WithContext(ctx context.Context, v EventLogV2) error
	VisitMetricLogV1WithContext(ctx context.Context, v MetricLogV1) error
	VisitAuditLogV2WithContext(ctx context.Context, v AuditLogV2) error
	VisitDiagnosticLogV1WithContext(ctx context.Context, v DiagnosticLogV1) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewWrappedLogV1PayloadFromServiceLogV1(v ServiceLogV1) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "serviceLogV1", serviceLogV1: &v}
}

func NewWrappedLogV1PayloadFromRequestLogV2(v RequestLogV2) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "requestLogV2", requestLogV2: &v}
}

func NewWrappedLogV1PayloadFromTraceLogV1(v TraceLogV1) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "traceLogV1", traceLogV1: &v}
}

func NewWrappedLogV1PayloadFromEventLogV2(v EventLogV2) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "eventLogV2", eventLogV2: &v}
}

func NewWrappedLogV1PayloadFromMetricLogV1(v MetricLogV1) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "metricLogV1", metricLogV1: &v}
}

func NewWrappedLogV1PayloadFromAuditLogV2(v AuditLogV2) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "auditLogV2", auditLogV2: &v}
}

func NewWrappedLogV1PayloadFromDiagnosticLogV1(v DiagnosticLogV1) WrappedLogV1Payload {
	return WrappedLogV1Payload{typ: "diagnosticLogV1", diagnosticLogV1: &v}
}
